queueclient: queueclient.o queueADT3.o
	gcc -o queueclient queueclient.o queueADT3.o

queueclient.o: queueclient.c queueADT.h
	gcc -c queueclient.c

queueADT3.o: queueADT3.c queueADT.h
	gcc -c queueADT3.c
	
