stackclient: stackclient.o stackADT2.o
	gcc -o stackclient stackclient.o stackADT2.o

stackclient.o: stackclient.c stackADT2.h
	gcc -c stackclient.c

stackADT2.o: stackADT2.c stackADT2.h
	gcc -c stackADT2.c
	
