queueclient: queueclient.o queueADT2.o
	gcc -o queueclient queueclient.o queueADT2.o

queueclient.o: queueclient.c queueADT2.h
	gcc -c queueclient.c

queueADT2.o: queueADT2.c queueADT2.h
	gcc -c queueADT2.c
	
